spring:
  datasource:
    url: jdbc:mysql://local.docker.mysql:3306/uamdb
    # username:
    # password:
  data:
    redis:
      host: local.docker.redis
      port: 6379
      # password:
      timeout: 60000
