spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orgdb
    # username:
    # password:
  data:
    redis:
      host: localhost
      port: 6379
      # password:
      timeout: 60000
  kafka:
    bootstrap-servers: localhost:9092
