spring:
  datasource:
    url: jdbc:mysql://local.docker.mysql:3306/orgdb
    # username:
    # password:
  data:
    redis:
      host: local.docker.redis
      port: 6379
      # password:
      timeout: 60000
  kafka:
    bootstrap-servers: kafka:9092 # use the Docker Compose service name if in the same network
