server:
  port: 8081
  shutdown: graceful

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: s02-cloud-config
  profiles:
    active: vault, git, dev
  cloud:
    bus:
      enabled: true
      destination: cloud-config-bus
      refresh:
        enabled: true
  kafka:
    client-id: cloud-config-producer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      properties:
        linger.ms: 5
        batch.size: 16384
        compression.type: snappy
    consumer:
      group-id: cloud-config-bus-group
      auto-offset-reset: latest
    properties:
      security.protocol: PLAINTEXT  # Use 'SSL' or 'SASL_SSL' if secure
      # Uncomment below if you use SASL/SSL authentication
      # sasl.mechanism: PLAIN
      # sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="kafka_user" password="kafka_pass";


# Logger
logging:
  file:
    name: "./config/log/cloud-config.log"
  level:
    com.cv: info
    org.hibernate: info
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.stat: trace
    org.hibernate.SQL_SLOW: info
    org.hibernate.cache: debug
  logback:
    rollingpolicy:
      max-file-size: 100MB
      clean-history-on-start: true
#Actuator
management:
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
