spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/creatorsventure/s02-cloud-config
          search-paths: properties/**
          defaultLabel: main

        vault:
          host: localhost             # <-- Vault host
          port: 8200                  # <-- Vault port
          scheme: http                # <-- use https in prod
          backend: kv                 # <-- Vault secret or kv depends on vault engine
          default-key: app-secret     # <-- fallback context for all apps
          profile-separator: '-'      # <-- resolves secret/app-secret-dev, etc.
          authentication: TOKEN       # <-- required explicitly
          token: ${VAULT_TOKEN}       # <-- Vault token (dev-only)
          kv-version: 2
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
