server:
  port: 8081
  shutdown: graceful

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: s02-cloud-config
  profiles:
    active: vault, git, dev
  cloud:
    bus:
      enabled: true

# Logger
logging:
  file:
    name: "./config/log/cloud-config.log"
  level:
    com.cv: info
    org.hibernate: info
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.stat: trace
    org.hibernate.SQL_SLOW: info
    org.hibernate.cache: debug
  logback:
    rollingpolicy:
      max-file-size: 100MB
      clean-history-on-start: true
#Actuator
management:
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
