# Redis Props
spring:
  cache:
    type: redis
    redis:
      time-to-live: 60000
  data:
    redis:
      host: localhost
      port: 6379
      password: redis123
      timeout: 60000
#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

# security Configurations
# Keystore
security:
  # The below commented properties will be loaded from vault
  #keystorePath: ${vault.keystorePath}
  #keystorePassword: ${vault.keystorePassword}
  # Current key alias + password
  #keystoreCurrentAlias:
  #name: ${vault.keystoreCurrentAlias.name}
  #keyPassword: ${vault.keystoreCurrentAlias.keyPassword}
  # Old (expired) keys
  #keystoreOldAliases:
  #- name: ${vault.keystoreOldAliases.0.name}
  #keyPassword: ${vault.keystoreOldAliases.0.keyPassword}
  # JWT
  #JWTSecret: ${vault.JWTSecret}
  # 15 minutes
  JWTAccessTokenExpirationMins: 15
  # 7 days
  JWTRefreshTokenExpirationMins: 10080
