# Dev tools
spring:
  messages:
    encoding: UTF-8
  devtools:
    restart:
      log-condition-evaluation-delta: false
  cloud:
    bus:
      enabled: true
      destination: ${app.kafka.config-bus.topic}

# Logger
logging:
  level:
    com.cv: info
    org.hibernate: info
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.stat: trace
    org.hibernate.SQL_SLOW: info
    org.hibernate.cache: debug
  logback:
    rollingpolicy:
      max-file-size: 100MB
      clean-history-on-start: true
# Server
server:
  shutdown: graceful
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: always

#Actuator
management:
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
app:
  kafka:
    config-bus:
      topic: cloud-config-bus
    notify-service:
      client-id: notify-service
      topic: notify-service
      group: notify-service-group
    org-service:
      client-id: org-service
      group: org-service-group
