#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://local.docker.service-registry:8761/eureka
  instance:
    hostname: local.docker.service-registry

# security Configurations
# Keystore
security:
  # 15 minutes
  JWTAccessTokenExpirationMins: 15
  # 7 days
  JWTRefreshTokenExpirationMins: 10080
