# security Configurations
# Keystore
security:
  # 15 minutes
  JWTAccessTokenExpirationMins: 15
  # 7 days
  JWTRefreshTokenExpirationMins: 10080

eureka:
  instance:
    hostname: host.docker.internal   # 👈 for Docker-to-host routing
    prefer-ip-address: false         # 👈 use hostname in registry
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://local.service-registry.docker:8761/eureka/
app:
  api-gateway:
    org-service:
      reset-password-url: http://localhost:8080/api/org-service/password/reset-password?id=
