#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

# security Configurations
# Keystore
security:
  # 15 minutes
  JWTAccessTokenExpirationMins: 15
  # 7 days
  JWTRefreshTokenExpirationMins: 10080
