spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notifydb
    # username:
    # password:
  data:
    redis:
      host: localhost
      port: 6379
      # password:
      timeout: 60000
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: e944d00f050b4c
    password: b7e94efd32a77e
  kafka:
    # List of Kafka broker addresses. Use Docker Compose service name if Notify runs in same Docker network
    bootstrap-servers: kafka:9092
