# Logger
logging:
  file:
    name: "./config/log/notify-service.log"
#Datasource
spring:
  #JPA
  jpa:
    properties:
      spring:
        datasource:
          initialize: true
    hibernate:
      jdbc:
        lob:
          non_contextual_creation: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      ddl-auto: none
    show-sql: true
  # Redis
  data:
    redis:
      repositories:
        enabled: false
  datasource:
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 1000
      idle-timeout: 10000
  # Redis Props
  cache:
    type: redis
    redis:
      time-to-live: 60000
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  cloud:
    stream:
      bindings:
        springCloudBusInput:
          group: ${app.notify-service.kafka.group}

  # Kafka
  kafka:
    client-id: ${app.notify-service.kafka.client-id}
    consumer:
      group-id: ${app.notify-service.kafka.group}
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
    listener:
      missing-topics-fatal: false
      ack-mode: manual
