spring:
  datasource:
    url: jdbc:mysql://localhost:3306/unitdb
    # username:
    # password:
  data:
    redis:
      host: localhost
      port: 6379
      # password:
      timeout: 60000
  kafka:
    bootstrap-servers: kafka:9092 # use the Docker Compose service name if in the same network
