spring:
  datasource:
    url: jdbc:mysql://local.mysql.docker:3306/unitdb
    # username:
    # password:
  data:
    redis:
      host: local.redis.docker
      port: 6379
      # password:
      timeout: 60000
  kafka:
    bootstrap-servers: localhost:9092
