spring:
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/apienginedb
    pool:
      initial-size: 10           # Enough for warming up
      max-size: 100              # <80ms query latency
      max-idle-time: 60s
      max-acquire-time: 5s
      max-create-connection-time: 5s
      validation-query: SELECT 1
  data:
    redis:
      host: local.redis.docker
      port: 6379
      timeout: 60000
  kafka:
    bootstrap-servers: localhost:9092
