# Logger
logging:
  file:
    name: "./config/log/api-engine.log"

spring:
  data:
    redis:
      client-type: lettuce
      repositories:
        enabled: false
  # Redis Props
  cache:
    type: redis
  cloud:
    stream:
      bindings:
        springCloudBusInput:
          group: ${app.api-engine.kafka.group}
  kafka:
    client-id: ${app.api-engine.kafka.client-id}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
        linger.ms: 10
        batch.size: 16384
        acks: all
        retries: 3
        enable.idempotence: true
    consumer:
      group-id: ${app.api-engine.kafka.group}
      auto-offset-reset: latest
